apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.global.vault.tokenName }}"
  namespace: {{ include "mongodb.namespace" . | quote }}
data:
  token: "{{ .Values.global.vault.token | b64enc }}"

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.global.vault.secretStoreName }}
  namespace: {{ include "mongodb.namespace" . | quote }}
spec:
  provider:
    vault:
      server: "{{ .Values.global.vault.url }}:{{ .Values.global.vault.port }}"
      path: "{{ .Values.global.vault.kv.path }}"
      version: "{{ .Values.global.vault.kv.version }}"
      auth:
        tokenSecretRef:
          name: "{{ .Values.global.vault.tokenName }}"
          key: "token"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-credentials
  namespace: {{ include "mongodb.namespace" . | quote }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.global.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.global.vault.secretPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.global.vault.secretPath }}
        property: password 
