apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Values.backend.name }}-configmap"
  namespace: {{ .Values.namespace }}
data:
  mongoPort: "{{ .Values.backend.mongoPort }}"
  backendPort: "{{ .Values.backend.container.port }}"
