apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mongo-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.global.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.vault.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: {{ .Values.global.vault.secretPath }}
        property: username
    - secretKey: password
      remoteRef:
        key: {{ .Values.global.vault.secretPath }}
        property: password 
